# Generated by Django 5.0.6 on 2024-06-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/staff/')),
                ('position', models.CharField(choices=[('Engineer', 'engineer'), ('Worker', 'worker'), ('Accountant', 'accountant'), ('Manager', 'manager'), ('Guard', 'guard')], default='Worker', max_length=50)),
                ('last_update', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='staff_staff_id_c7b100_idx')],
            },
        ),
    ]
