# Generated by Django 5.0.6 on 2024-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
