# Generated by Django 5.0.6 on 2024-06-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/blog/post/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveBigIntegerField(default=2024)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='media/blog/post/')),
                ('text', models.TextField()),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('month', models.CharField(choices=[('Jan', 'january'), ('Feb', 'february'), ('Mar', 'march'), ('Apr', 'april'), ('May', 'may'), ('June', 'june'), ('July', 'july'), ('Aug', 'august'), ('Sep', 'september'), ('Oct', 'october'), ('Nov', 'november'), ('Dec', 'december')], default='Jan', max_length=100)),
                ('last_update', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.creator')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.date')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.year')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='blog_blogpo_id_f557c2_idx')],
            },
        ),
    ]
